### ISSUE TITLE
Gollum 0.9.8 not work on arm64

### ISSUE THREAD

**Issue by LSDsl** [ComThings/PandwaRF#52]
Hi. Cannot use last lib on arm64 device (test device Xiaomi Redmi Note 3)

```java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.test.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.test.app-2/lib/arm64, /data/app/com.test.app-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_shared.so"```
```E/Sub1GHzRfTransceiver: Couldn't load the stlport_shared library``` and cannot load any library
```E/Sub1GHzRfBleTransceiver:  Failed to load any of the known C++ library```
so when try use sdk - app crash
```E/art: No implementation found for int com.comthings.gollum.api.gollumandroidlib.Sub1GHzRfTransceiver.native_rfClose(int) (tried Java_com_comthings_gollum_api_gollumandroidlib_Sub1GHzRfTransceiver_native_1rfClose and Java_com_comthings_gollum_api_gollumandroidlib_Sub1GHzRfTransceiver_native_1rfClose__I)```

P.S. Gollum 0.9.3 work fine

**Comment by trollwookiee** [comment]
This is because I enabled multiple ABI in library, but some of the libraries cannot be found on some ABI (eg. arm64-v8a)
So I have reverted to single ABI: armeabi-v7a.

Can you please check with https://github.com/ComThings/PandwaRF/commit/82b41307cfe695945d6165ca84fd6d2238b3d024 and 'com.comthings.pandwarf:gollum:0.9.9' ? 
Thanks
